# config.py
import os

# ---------- Telegram ----------
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', 'YOUR_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', 'YOUR_CHAT_ID')

# ---------- Features ----------
ENABLE_PRICE_FETCH = True          # fetch 5-day price return via yfinance

# ---------- Scoring ----------
BUY_THRESHOLD = 70
WATCH_THRESHOLD = 50
MIN_LIQUIDITY = 5_00_00_000       # 5 Crore

# ---------- Stock Lists ----------
# Nifty 50
NIFTY_50 = [
    'RELIANCE', 'TCS', 'HDFCBANK', 'INFY', 'HINDUNILVR',
    'ICICIBANK', 'SBIN', 'KOTAKBANK', 'LT', 'BHARTIARTL',
    'ITC', 'WIPRO', 'HCLTECH', 'ASIANPAINT', 'TITAN',
    'MARUTI', 'TATAMOTORS', 'SUNPHARMA', 'NTPC', 'POWERGRID',
    'TATASTEEL', 'BAJFINANCE', 'AXISBANK', 'HDFC', 'ULTRACEMCO',
    'ADANIPORTS', 'GRASIM', 'JSWSTEEL', 'DIVISLAB', 'DRREDDY',
    'HINDALCO', 'EICHERMOT', 'COALINDIA', 'BRITANNIA', 'TATACONSUM',
    'HEROMOTOCO', 'BAJAJ-AUTO', 'APOLLOHOSP', 'ONGC', 'SBILIFE',
    'M&M', 'INDUSINDBK', 'UPL', 'PIDILITIND', 'DABUR',
    'MCDOWELL-N', 'BAJAJFINSV', 'TECHM', 'SHRIRAMFIN', 'HDFCLIFE'
]

# Nifty Next 50
NIFTY_NEXT_50 = [
    'VEDL', 'HINDZINC', 'JINDALSTEL', 'BANKBARODA', 'CANBK',
    'GODREJCP', 'HAL', 'BEL', 'SIEMENS', 'ABB',
    'HAVELLS', 'DIXON', 'ACC', 'BERGEPAINT', 'PAGEIND',
    'COLPAL', 'DALBHARA', 'MUTHOOTFIN', 'CHOLAFIN', 'SRTRANSFIN',
    'PEL', 'VOLTAS', 'CUMMINSIND', 'SKFINDIA', 'DEEPAKNTR',
    'FACT', 'NATIONALUM', 'TATACHEM', 'PETRONET', 'GAIL',
    'HPCL', 'BPCL', 'IOC', 'MOTHERSUMI', 'INDIGO',
    'SPARC', 'LUPIN', 'AUROPHARMA', 'CIPLA', 'TORNTPHARM',
    'GLENMARK', 'BIOCON', 'ZYDUSLIFE', 'SUNTV', 'ZEEL',
    'TVSMOTOR', 'BALKRISIND', 'MRF', 'MUTHOOT', 'ICICIPRULI'
]

# Nifty Midcap 100 (sample)
NIFTY_MIDCAP_100 = [
    'ADANIENT', 'ADANIGREEN', 'GMRINFRA', 'L&T', 'SIEMENS',
    'BHEL', 'PFC', 'RECLTD', 'ADANITRANS', 'MUTHOOTFIN',
    'CHOLAFIN', 'MANAPPURAM', 'SHRIRAMFIN', 'ICICIGI', 'HDFCAMC',
    'SBICARD', 'POLYCAB', 'HONEYWELL', 'THERMAX', 'CROMPTON',
    'WHIRLPOOL', 'BLUESTAR', 'VOLTAS', 'HAVELLS', 'INDUSTOWER',
    'TATACOMM', 'TEJASNET', 'IDEA', 'GTLINFRA', 'NAUKRI',
    'ZOMATO', 'DMART', 'AVANTIFEED', 'RADICO', 'CCL',
    'VIPIND', 'PVRINOX', 'TITAN', 'SBI', 'JUBLFOOD',
    'DOMINO', 'BIKAJI', 'NESTLEIND', 'BRITANNIA', 'HATSUN',
    'VARUNBEV', 'VBL', 'ABFRL', 'ADITYABIRLA', 'MAHINDRA',
    'ASHOKLEY', 'ESCORTS', 'JSWENERGY', 'JSWINFRA', 'APOLLOTYRE',
    'CEATLTD', 'BANKINDIA', 'UNIONBANK', 'INDIANB', 'CENTRALBK',
    'PNB', 'UCOBANK', 'IDFCFIRSTB', 'BANDHANBNK', 'RBLBANK',
    'YESBANK', 'FEDERALBNK', 'KARNATAKAB', 'TMB', 'CUB',
    'CSBBANK', 'DCBBANK', 'KARURVYSYA', 'SOUTHBANK', 'J&KBANK',
    'DOLATALGO', 'ANGELONE', 'MOTILALOFS', 'HDFCSEC', 'BAJAJHLDNG',
    'BAJAJELEC', 'AWL', 'MAZDOCK', 'COCHINSHIP', 'HUDCO',
    'NBCC', 'IRFC', 'IREDA', 'DLF', 'GODREJPROP',
    'OBEROIRLTY', 'PRESTIGE', 'SOBHA', 'SUNTECK', 'PHOENIXLTD'
]

HIGH_LIQUIDITY_MIDCAPS = [
    'MINDTREE', 'LTIM', 'TECHM', 'WIPRO', 'MPHASIS',
    'PERSISTENT', 'CYIENT', 'COFORGE', 'KPITTECH', 'ZENSARTECH',
    'BIRLASOFT', 'LTI', 'NIITTECH', 'JBCHEPHARM', 'ALKEM',
    'TORNTPHARM', 'GLENMARK', 'BIOCON', 'AUROPHARMA', 'IPCA',
    'CADILAHC', 'SANOFI', 'GSK', 'MOTHERSON', 'BOSCH',
    'MINDACORP', 'ZF', 'SAMVRIDDHI', 'ASK', 'AISL',
    'SMLISUZU', 'ACC', 'AMBUJACEM', 'SHREECEM', 'RAMCOCEM',
    'HEIDELBERG', 'KCP', 'JKLAKSHMI', 'NCLIND', 'SAIL',
    'MOIL', 'KIOCL', 'ORIENTALRL', 'SUNFLAG', 'JAYASWAL',
    'MANALIPETC', 'RAJESHEXPO', 'HINDCOPPER', 'TATACHEM', 'DEEPAKNTR',
    'SRF', 'AARTIIND', 'PIIND', 'NAVINFLUOR', 'SOLARINDS',
    'ATUL', 'TATASTL', 'BHARTIARTL', 'JIO', 'IDEA',
    'GTLINFRA', 'TATACOMM', 'PFC', 'RECLTD', 'BANKBARODA',
    'CANBK', 'PNB', 'UCOBANK', 'IDFCFIRSTB', 'BANDHANBNK',
    'RBLBANK', 'YESBANK'
]

FULL_SCAN_STOCKS = list(set(NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP_100 + HIGH_LIQUIDITY_MIDCAPS))
QUICK_SCAN_STOCKS = NIFTY_50

DEFAULT_SCAN_MODE = 'full'   # 'quick' or 'full'
