# config.py
import os

# Telegram Settings
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', 'YOUR_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', 'YOUR_CHAT_ID')

# Price Fetching
ENABLE_PRICE_FETCH = True

# Scoring Thresholds
BUY_THRESHOLD = 70
WATCH_THRESHOLD = 50

# Liquidity Filter (in INR)
MIN_LIQUIDITY = 5_00_00_000  # 5 Crore

# ================================================================
# HIGH LIQUIDITY STOCK LIST (~280 stocks)
# Nifty 200 + Nifty Next 50 + Select Midcaps
# All have avg daily delivery > 5 Cr
# ================================================================
NIFTY_200 = [
    # ---- Nifty 50 (Top 50) ----
    'RELIANCE', 'TCS', 'HDFCBANK', 'INFY', 'HINDUNILVR',
    'ICICIBANK', 'SBIN', 'KOTAKBANK', 'LT', 'BHARTIARTL',
    'ITC', 'WIPRO', 'HCLTECH', 'ASIANPAINT', 'TITAN',
    'MARUTI', 'TATAMOTORS', 'SUNPHARMA', 'NTPC', 'POWERGRID',
    'TATASTEEL', 'BAJFINANCE', 'AXISBANK', 'HDFC', 'ULTRACEMCO',
    'ADANIPORTS', 'GRASIM', 'JSWSTEEL', 'DIVISLAB', 'DRREDDY',
    'HINDALCO', 'EICHERMOT', 'COALINDIA', 'BRITANNIA', 'TATACONSUM',
    'HEROMOTOCO', 'BAJAJ-AUTO', 'APOLLOHOSP', 'ONGC', 'SBILIFE',
    'M&M', 'INDUSINDBK', 'UPL', 'PIDILITIND', 'DABUR',
    'MCDOWELL-N', 'BAJAJFINSV', 'TECHM', 'SHRIRAMFIN', 'HDFCLIFE',

    # ---- Nifty Next 50 (51-100) ----
    'VEDL', 'HINDZINC', 'JINDALSTEL', 'BANKBARODA', 'CANBK',
    'GODREJCP', 'HAL', 'BEL', 'SIEMENS', 'ABB',
    'HAVELLS', 'DIXON', 'ACC', 'BERGEPAINT', 'PAGEIND',
    'COLPAL', 'DALBHARA', 'MUTHOOTFIN', 'CHOLAFIN', 'SRTRANSFIN',
    'PEL', 'VOLTAS', 'CUMMINSIND', 'SKFINDIA', 'DEEPAKNTR',
    'FACT', 'NATIONALUM', 'TATACHEM', 'PETRONET', 'GAIL',
    'HPCL', 'BPCL', 'IOC', 'MOTHERSUMI', 'EICHERMOT',
    'INDIGO', 'SPARC', 'LUPIN', 'AUROPHARMA', 'DIVISLAB',
    'CIPLA', 'TORNTPHARM', 'GLENMARK', 'BIOCON', 'ZYDUSLIFE',
    'SUNTV', 'ZEEL', 'TVSMOTOR', 'BALKRISIND', 'MRF',

    # ---- Nifty Midcap 100 (101-200) ----
    'ADANIENT', 'ADANIGREEN', 'GMRINFRA', 'L&T', 'SIEMENS',
    'BHEL', 'PFC', 'RECLTD', 'POWERGRID', 'ADANITRANS',
    'MUTHOOTFIN', 'CHOLAFIN', 'MANAPPURAM', 'SHRIRAMFIN', 'ICICIGI',
    'HDFCAMC', 'SBICARD', 'POLYCAB', 'HONEYWELL', 'THERMAX',
    'CROMPTON', 'WHIRLPOOL', 'BLUESTAR', 'VOLTAS', 'HAVELLS',
    'INDUSTOWER', 'TATACOMM', 'TEJASNET', 'IDEA', 'GTLINFRA',
    'NAUKRI', 'ZOMATO', 'DMART', 'AVANTIFEED', 'RADICO',
    'CCL', 'VIPIND', 'PVRINOX', 'TITAN', 'SBI',
    'JUBLFOOD', 'DOMINO', 'BIKAJI', 'NESTLEIND', 'BRITANNIA',
    'HATSUN', 'VARUNBEV', 'VBL', 'ABFRL', 'ADITYABIRLA',

    # ---- Additional High Liquidity Midcaps (201-230) ----
    'ASHOKLEY', 'ESCORTS', 'MAHINDRA', 'JSWENERGY', 'JSWINFRA',
    'APOLLOTYRE', 'CEATLTD', 'BANKINDIA', 'UNIONBANK', 'INDIANB',
    'CENTRALBK', 'PNB', 'UCOBANK', 'IDFCFIRSTB', 'BANDHANBNK',
    'RBLBANK', 'YESBANK', 'FEDERALBNK', 'KARNATAKAB', 'TMB',
    'CUB', 'CSBBANK', 'DCBBANK', 'KARURVYSYA', 'SOUTHBANK',
    'J&KBANK', 'DOLATALGO', 'ANGELONE', 'MOTILALOFS', 'HDFCSEC',
    # Financial Services
    'BAJAJHLDNG', 'BAJAJELEC', 'ADANIENT', 'AWL', 'MAZDOCK',
    'COCHINSHIP', 'HUDCO', 'NBCC', 'IRFC', 'IREDA',
    # Real Estate
    'DLF', 'GODREJPROP', 'OBEROIRLTY', 'PRESTIGE', 'SOBHA',
    'SUNTECK', 'PHOENIXLTD', 'BRIGADE', 'KOLTE-PATIL',
    # IT
    'MINDTREE', 'LTIM', 'TECHM', 'WIPRO', 'MPHASIS',
    'PERSISTENT', 'CYIENT', 'COFORGE', 'KPITTECH', 'ZENSARTECH',
    'BIRLASOFT', 'LTI', 'TECHM', 'NIITTECH',
    # Pharma
    'JBCHEPHARM', 'ALKEM', 'TORNTPHARM', 'GLENMARK', 'BIOCON',
    'AUROPHARMA', 'IPCA', 'CADILAHC', 'SANOFI', 'GSK',
    # Auto Ancillary
    'MOTHERSON', 'BOSCH', 'MINDACORP', 'MAHINDRA', 'ZF',
    'SAMVRIDDHI', 'ASK', 'AISL', 'SMLISUZU',
    # Cement
    'ACC', 'AMBUJACEM', 'SHREECEM', 'RAMCOCEM', 'HEIDELBERG',
    'KCP', 'JKLAKSHMI', 'NCLIND',
    # Metals
    'SAIL', 'MOIL', 'KIOCL', 'ORIENTALRL', 'SUNFLAG',
    'JAYASWAL', 'MANALIPETC', 'RAJESHEXPO', 'HINDCOPPER',
    # Chemicals
    'TATACHEM', 'DEEPAKNTR', 'SRF', 'AARTIIND', 'PIIND',
    'NAVINFLUOR', 'SOLARINDS', 'ATUL', 'TATASTL',
    # Telecom
    'BHARTIARTL', 'JIO', 'IDEA', 'GTLINFRA', 'TATACOMM',
    # NBFC
    'PFC', 'RECLTD', 'BANKBARODA', 'CANBK', 'PNB',
    'UCOBANK', 'IDFCFIRSTB', 'BANDHANBNK', 'RBLBANK', 'YESBANK'
]

# Default: Use NIFTY_200 if STOCKS_LIST is not set
STOCKS_LIST = NIFTY_200
